import React from "react";
import ReactDOM from "react-dom/client";
import { ArrowUpRight, Github, Linkedin, Mail, Menu, X } from "lucide-react";
import "./styles.css";

const projects = [
  { number:"01", title:"TimeOut of Gaborone", type:"Building · Software", description:"A hyperlocal discovery platform for finding places, experiences and things to do around Gaborone.", tags:["C#","ASP.NET Core MVC","EF Core","SQL"], href:"https://github.com/wrightSBT", accent:"lime" },
  { number:"02", title:"Opportunity Board", type:"Product · Platform", description:"A platform concept designed to make opportunities, resources and pathways easier for young people to discover.", tags:["TypeScript","UI/UX","Web"], href:"https://github.com/wrightSBT/Opportunity-Board", accent:"blue" },
  { number:"03", title:"TWS Digital", type:"Business · Web", description:"A digital solutions initiative helping businesses build stronger online experiences and customer journeys.", tags:["HTML","CSS","JavaScript","Figma"], href:"https://github.com/wrightSBT/TWS-Digital", accent:"orange" },
  { number:"04", title:"Health Haven", type:"Product · Health Tech", description:"A wellness technology concept exploring personalised roadmaps, wearable data and digital wellness experiences.", tags:["Product","UX/UI","Web"], href:"https://github.com/wrightSBT/Health-Haven", accent:"violet" }
];
const experience = [
  { period:"2025 — Present", role:"Technical Lead & Product Development", company:"Sebatech Communications", description:"Working across technology strategy, enterprise infrastructure proposals, product development and client technology solutions." },
  { period:"2025 — Present", role:"Founder · Digital Solutions", company:"TWS Digital", description:"Building web experiences and digital solutions for businesses while developing product, UX and client delivery skills." },
  { period:"2025 — Present", role:"Co-Founder · Product & Technology", company:"Health Haven", description:"Exploring the intersection of wellness, technology, data and personalised digital experiences." },
  { period:"2025 — Present", role:"Technology & Community Engagement", company:"Gaborone AI Hub", description:"Supporting technology initiatives, webinars and community programmes focused on AI and digital skills." }
];
function App(){
 const [open,setOpen]=React.useState(false); const close=()=>setOpen(false);
 return <div className="site">
  <header className="nav-wrap"><nav className="nav container"><a className="brand" href="#top" onClick={close}>TS<span>.</span></a><button className="menu-btn" aria-label={open?"Close menu":"Open menu"} onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}</button><div className={`nav-links ${open?"is-open":""}`}><a href="#work" onClick={close}>Work</a><a href="#about" onClick={close}>About</a><a href="#experience" onClick={close}>Experience</a><a href="#contact" onClick={close}>Contact</a><a className="nav-cta" href="mailto:wrightsebate@gmail.com" onClick={close}>Let's talk <ArrowUpRight size={15}/></a></div></nav></header>
  <main id="top">
   <section className="hero container"><div className="eyebrow"><span className="status-dot"/>Available for internships & opportunities</div><h1>I build digital products,<br/><em>systems & experiences.</em></h1><div className="hero-bottom"><p className="hero-copy">I'm Tshiamo Sebate, an Applied Business Computing student in Botswana. I combine software development, systems thinking and product design to turn ideas and real-world problems into practical digital solutions.</p><div className="hero-actions"><a className="button button-dark" href="#work">View my work <ArrowUpRight size={17}/></a><a className="button button-light" href="https://github.com/wrightSBT" target="_blank" rel="noreferrer"><Github size={17}/>GitHub</a></div></div><div className="hero-meta"><span>Gaborone, Botswana</span><span>BSc (Hons) Applied Business Computing</span><span>Software · Systems · Product</span></div></section>
   <section id="work" className="section work-section"><div className="container"><div className="section-heading"><span className="section-kicker">01 / Selected work</span><h2>Things I'm building.</h2><p>A selection of products, experiments and digital solutions across software, business and technology.</p></div><div className="projects">{projects.map(p=><a className={`project-card ${p.accent}`} href={p.href} target="_blank" rel="noreferrer" key={p.number}><div className="project-top"><span>{p.number}</span><ArrowUpRight size={21}/></div><div className="project-content"><span className="project-type">{p.type}</span><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></a>)}</div></div></section>
   <section id="about" className="section about-section"><div className="container about-grid"><div className="section-heading"><span className="section-kicker">02 / About</span><h2>Technology is most interesting when it solves something real.</h2></div><div className="about-copy"><p>My background in Applied Business Computing has exposed me to software development, systems analysis, databases, networking, cloud computing and information security.</p><p>Outside university, I've been experimenting with my own products, working on business technology projects and building digital experiences for local businesses.</p><p>Right now, I'm focused on becoming a stronger software developer while learning how good products and business systems are actually designed, built and deployed.</p></div></div></section>
   <section id="experience" className="section experience-section"><div className="container"><div className="section-heading"><span className="section-kicker">03 / Experience</span><h2>Where I've been putting it into practice.</h2></div><div className="experience-list">{experience.map(e=><article className="experience-item" key={e.company}><span className="experience-period">{e.period}</span><div><h3>{e.role}</h3><h4>{e.company}</h4><p>{e.description}</p></div></article>)}</div></div></section>
   <section className="section capabilities-section"><div className="container capabilities-grid"><div className="section-heading"><span className="section-kicker">04 / Toolkit</span><h2>What I work with.</h2></div><div className="capability-groups"><div className="capability"><span>Development</span><p>C# · HTML · CSS · JavaScript · TypeScript</p></div><div className="capability"><span>Currently learning</span><p>ASP.NET Core MVC · EF Core · SQL Server · Full-Stack Development</p></div><div className="capability"><span>Tools</span><p>Git · GitHub · Visual Studio · VS Code · Figma</p></div><div className="capability"><span>Foundations</span><p>Systems Development · Database Design · Networking · Cloud · Information Security</p></div></div></div></section>
   <section className="section building-section"><div className="container building-card"><div><span className="section-kicker">05 / Currently building</span><h2>TimeOut of Gaborone</h2><p>I'm using TimeOut as my first serious ASP.NET Core MVC project — not just to build the product, but to understand how professional applications are structured from the inside.</p></div><div className="build-stack"><span>Research</span><i>→</i><span>Design</span><i>→</i><span>Development</span><i>→</i><span>Testing</span><i>→</i><span>Deploy</span></div></div></section>
   <section id="contact" className="contact-section"><div className="container contact-inner"><span className="section-kicker">06 / Contact</span><h2>Let's build something useful.</h2><p>I'm open to internship opportunities, interesting technical projects and conversations with people building useful things.</p><div className="contact-links"><a href="mailto:wrightsebate@gmail.com"><Mail size={18}/>Email</a><a href="https://www.linkedin.com/in/tshiamo-sebate-a554bb292/" target="_blank" rel="noreferrer"><Linkedin size={18}/>LinkedIn</a><a href="https://github.com/wrightSBT" target="_blank" rel="noreferrer"><Github size={18}/>GitHub</a></div></div></section>
  </main><footer className="footer container"><span>© 2026 Tshiamo Sebate</span><span>Built with React + TypeScript</span></footer>
 </div>
}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
